version: '2'
services:
  nginx:
    image: nginx:latest
    ports:
      - "8000:8000"
    volumes:
      - ./conf/nginx:/etc/nginx/conf.d
      - /static:/app/static
    depends_on:
      - django
  django:
    build: .
    container_name: djangostocks
    volumes:
      - /static:/app/static
    environment:
      # Set DEBUG=false, let nginx handle static files
      - DEBUG=False
      - QUOTES_URL=http://nginx:8000/static/quotes_data.json
